import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const flemmatico = localFont({
  src: [
    { path: "./fonts/Flemmatico Thin.woff2", weight: "200", style: "normal" },
    { path: "./fonts/Flemmatico Light.woff2", weight: "300", style: "normal" },
    {
      path: "./fonts/Flemmatico Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Flemmatico Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    { path: "./fonts/Flemmatico Bold.woff2", weight: "700", style: "normal" },
    { path: "./fonts/Flemmatico Black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-flemmatico",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
          rel="stylesheet"
        />
      </head>
      <body className={`${flemmatico.variable} antialiased`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
